remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta Annotations]
description: [Jakarta Annotations defines a collection of annotations representing common semantic concepts that enable a declarative style of programming that applies across a variety of Java technologies.]

links:
  source: https://github.com/eclipse-ee4j/common-annotations-api
  javadocs: apidocs/
  download: https://github.com/eclipse-ee4j/common-annotations-api/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/ca-dev
  #faq: FAQ
